feat: competition list
EUREKA-ITB/eureka-itb24 pull request #28
Opened 2024-05-23 08:46 UTC by ARoyyanF

design:
localhost:3000/main

current placeholders:
- description
- image

ingfokan revisi wkw

2024-05-23 09:13 UTC, mafiefa02 commented
oke sih, mantap! @ARoyyanF supaya lebih reusable + composable, komponen ini ![image](https://github.com/EUREKA-ITB/eureka-itb24/assets/91366510/37f9ad99-f3cd-4327-bfa2-bc1ea541d6ce) bisa dipisah jadi component sendiri (misal `CompetitionItem.tsx`), jadi nanti bisa punya list of competitions kek gini
```typescript
type ICompetitionsList = {
  name: string;
  levels: string[];
  description: string;
  image: StaticImageData;
};

const competitions: ICompetitionsList[] = [
    {
      name: "Physics Olympiad",
      levels: ["SD/MI", "SMP/MTs"],
      description: "Lorem ipsum dolor sit amet.",
      image: olympiadIcon,
    },
    {
      name: "Scientific Writing",
      levels: ["SD/MI", "SMP/MTs"],
      description: "Lorem ipsum dolor sit amet.",
      image: scientificWritingIcon,
    },
  ];
```
contoh cara pake componentnya begini
```tsx
<div className="flex size-full h-screen flex-col items-center justify-center gap-8">
    {competitions.map((competition, index) => (
        <CompetitionItem
            key={index}
            competition={competition}
          />
      ))}
</div>
```
jadi keliatan lebih clean dan gampang ubahnya 😁

2024-05-29 12:00 UTC, mafiefa02 requested changes

2024-05-29 12:00 UTC, mafiefa02 commented on src/components/CompetitionItems.tsx
> +            <div className="my-auto flex-row space-x-4 space-y-4 md:space-y-0 ">
idenya tuh biar bagian ini ga diulang-ulang (klo sekarang kan ditulis manual 3 kali buat 3 cabang lomba)

nah coba bikin komponen `CompetitionItems` ini buat bisa accept beberapa props, yang nantinya ditampilin di dalemnya, kek gini kurang lebih
 
```tsx
export default function CompetitionItems({
	competition,
}: {
	competition: TCompetitions;
}) {
	<div className="flex flex-row space-x-5">
		<div className="my-auto hidden w-20 flex-shrink-0 sm:block">
			<Image src={competition.image} alt="item" />
		</div>
		<div className="flex flex-col space-y-2">
			<div className="flex flex-col justify-between md:flex-row">
				<div className="text-4xl font-bold">{competition.title}</div>
				<div className="my-auto flex-row space-x-4 space-y-4 md:space-y-0 ">
					{competition.levels.map((level) => (
						<Badge variant="default">{level}</Badge>
					))}
				</div>
			</div>
			<p>{competition.description}</p>
		</div>
	</div>;
}
```

type `TCompetitions` bisa ngikut types yang udah ditulis. cara make componentnya gimana? bisa contoh ini di file `app/main/page.tsx`

```tsx
const competitions: TCompetitions[] = [
	{
		name: 'PHYSICS OLYMPIAD',
		levels: ['SMP/MTs', 'SD/MI'],
		description:
			"We're no strangers to love You know the rules and so do I (do I) A full commitment's what I'm thinking of You wouldn't get this from any other guy I just wanna tell you how I'm feeling Gotta make you understand",
		image: 'sciWriting.svg',
	},
	{
		name: 'SCIENTIFIC WRITING',
		levels: ['SMP/MTs', 'SD/MI'],
		description:
			'Never gonna give you up Never gonna let you down Never gonna run around and desert you Never gonna make you cry Never gonna say goodbye Never gonna tell a lie and hurt you',
		image: 'sciWriting.svg',
	},
];

export default function Competition_List() {
	return (
		<div className="flex flex-col space-y-10 px-20 xl:container xl:px-20">
			<div className="flex flex-col items-center text-center">
				<h1 className="text-5xl font-bold italic">COMPETITIONS</h1>
				<h2 className="text-2xl font-light">
					Things that are waiting beyond the horizon
				</h2>
			</div>

			{competitions.map((competition) => (
				<CompetitionItem competition={competition} />
			))}
		</div>
	);
}

```

2024-05-29 12:01 UTC, mafiefa02 commented on src/components/CompetitionItems.tsx
> +            <div className="my-auto flex-row space-x-4 space-y-4 md:space-y-0 ">
EH MAAP, ternyata dah diganti ya

2024-05-29 12:02 UTC, mafiefa02 commented on src/components/CompetitionItems.tsx
> +            <div className="my-auto flex-row space-x-4 space-y-4 md:space-y-0 ">
salah liat

2024-05-29 12:03 UTC, mafiefa02 commented on src/components/CompetitionItems.tsx
> +            <div className="my-auto flex-row space-x-4 space-y-4 md:space-y-0 ">
ntar tak review lagi

2024-05-29 13:18 UTC, ARoyyanF commented on src/components/CompetitionItems.tsx
> +            <div className="my-auto flex-row space-x-4 space-y-4 md:space-y-0 ">
Bruh

2024-05-29 13:24 UTC, ARoyyanF commented on src/components/CompetitionItems.tsx
> +            <div className="my-auto flex-row space-x-4 space-y-4 md:space-y-0 ">
.map() kalo gk pake key eslintnya marah marah

2024-05-29 13:33 UTC, ARoyyanF commented on src/components/CompetitionItems.tsx
> +            <div className="my-auto flex-row space-x-4 space-y-4 md:space-y-0 ">
> EH MAAP, ternyata dah diganti ya

Nampaknya perlu diganti lagi karena yg dibikin "composable" kebalik wkwkw

2024-05-29 13:57 UTC, mafiefa02 commented on src/components/CompetitionItems.tsx
> +            <div className="my-auto flex-row space-x-4 space-y-4 md:space-y-0 ">
> .map() kalo gk pake key eslintnya marah marah

yes emang harusnya gini, working as intended

2024-05-30 20:33 UTC, mafiefa02 commented
nice, lgtm

2024-05-30 20:33 UTC, mafiefa02 approved these changes

2024-05-30 20:38 UTC, merged

2024-05-30 20:43 UTC, mafiefa02 commented
Task linked: [CU-86epa7zud Competitions list component](https://app.clickup.com/t/86epa7zud)